//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SmartRentalsEntities : DbContext
    {
        public SmartRentalsEntities()
            : base("name=SmartRentalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<C_Admin_Rentals> C_Admin_Rentals { get; set; }
    
        public virtual int sp_EliminarAdminRental(Nullable<int> v_id)
        {
            var v_idParameter = v_id.HasValue ?
                new ObjectParameter("v_id", v_id) :
                new ObjectParameter("v_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarAdminRental", v_idParameter);
        }
    
        public virtual int sp_InsertarAdminRental(string v_Cedula, string v_Nombre, string v_SegundoNombre, string v_PrimerApellido, string v_SegundoApellido, Nullable<System.DateTime> v_FechaNacimiento, string v_TelefonoCasa, string v_TelefonoCelular, string v_Email)
        {
            var v_CedulaParameter = v_Cedula != null ?
                new ObjectParameter("v_Cedula", v_Cedula) :
                new ObjectParameter("v_Cedula", typeof(string));
    
            var v_NombreParameter = v_Nombre != null ?
                new ObjectParameter("v_Nombre", v_Nombre) :
                new ObjectParameter("v_Nombre", typeof(string));
    
            var v_SegundoNombreParameter = v_SegundoNombre != null ?
                new ObjectParameter("v_SegundoNombre", v_SegundoNombre) :
                new ObjectParameter("v_SegundoNombre", typeof(string));
    
            var v_PrimerApellidoParameter = v_PrimerApellido != null ?
                new ObjectParameter("v_PrimerApellido", v_PrimerApellido) :
                new ObjectParameter("v_PrimerApellido", typeof(string));
    
            var v_SegundoApellidoParameter = v_SegundoApellido != null ?
                new ObjectParameter("v_SegundoApellido", v_SegundoApellido) :
                new ObjectParameter("v_SegundoApellido", typeof(string));
    
            var v_FechaNacimientoParameter = v_FechaNacimiento.HasValue ?
                new ObjectParameter("v_FechaNacimiento", v_FechaNacimiento) :
                new ObjectParameter("v_FechaNacimiento", typeof(System.DateTime));
    
            var v_TelefonoCasaParameter = v_TelefonoCasa != null ?
                new ObjectParameter("v_TelefonoCasa", v_TelefonoCasa) :
                new ObjectParameter("v_TelefonoCasa", typeof(string));
    
            var v_TelefonoCelularParameter = v_TelefonoCelular != null ?
                new ObjectParameter("v_TelefonoCelular", v_TelefonoCelular) :
                new ObjectParameter("v_TelefonoCelular", typeof(string));
    
            var v_EmailParameter = v_Email != null ?
                new ObjectParameter("v_Email", v_Email) :
                new ObjectParameter("v_Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarAdminRental", v_CedulaParameter, v_NombreParameter, v_SegundoNombreParameter, v_PrimerApellidoParameter, v_SegundoApellidoParameter, v_FechaNacimientoParameter, v_TelefonoCasaParameter, v_TelefonoCelularParameter, v_EmailParameter);
        }
    
        public virtual int sp_ModificarAdminRental(Nullable<int> v_id_admin, string v_cedula, string v_nombre, string v_segundonombre, string v_primerapellido, string v_segundoapellido, Nullable<System.DateTime> v_fechanacimiento, string v_telefonocasa, string v_telefonocelular, string v_email)
        {
            var v_id_adminParameter = v_id_admin.HasValue ?
                new ObjectParameter("v_id_admin", v_id_admin) :
                new ObjectParameter("v_id_admin", typeof(int));
    
            var v_cedulaParameter = v_cedula != null ?
                new ObjectParameter("v_cedula", v_cedula) :
                new ObjectParameter("v_cedula", typeof(string));
    
            var v_nombreParameter = v_nombre != null ?
                new ObjectParameter("v_nombre", v_nombre) :
                new ObjectParameter("v_nombre", typeof(string));
    
            var v_segundonombreParameter = v_segundonombre != null ?
                new ObjectParameter("v_segundonombre", v_segundonombre) :
                new ObjectParameter("v_segundonombre", typeof(string));
    
            var v_primerapellidoParameter = v_primerapellido != null ?
                new ObjectParameter("v_primerapellido", v_primerapellido) :
                new ObjectParameter("v_primerapellido", typeof(string));
    
            var v_segundoapellidoParameter = v_segundoapellido != null ?
                new ObjectParameter("v_segundoapellido", v_segundoapellido) :
                new ObjectParameter("v_segundoapellido", typeof(string));
    
            var v_fechanacimientoParameter = v_fechanacimiento.HasValue ?
                new ObjectParameter("v_fechanacimiento", v_fechanacimiento) :
                new ObjectParameter("v_fechanacimiento", typeof(System.DateTime));
    
            var v_telefonocasaParameter = v_telefonocasa != null ?
                new ObjectParameter("v_telefonocasa", v_telefonocasa) :
                new ObjectParameter("v_telefonocasa", typeof(string));
    
            var v_telefonocelularParameter = v_telefonocelular != null ?
                new ObjectParameter("v_telefonocelular", v_telefonocelular) :
                new ObjectParameter("v_telefonocelular", typeof(string));
    
            var v_emailParameter = v_email != null ?
                new ObjectParameter("v_email", v_email) :
                new ObjectParameter("v_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarAdminRental", v_id_adminParameter, v_cedulaParameter, v_nombreParameter, v_segundonombreParameter, v_primerapellidoParameter, v_segundoapellidoParameter, v_fechanacimientoParameter, v_telefonocasaParameter, v_telefonocelularParameter, v_emailParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAdminRental_Result> sp_RetornaAdminRental(string v_cedula, string v_nombre, string v_segundonombre, string v_apellido, string v_segundoapellido, string v_email)
        {
            var v_cedulaParameter = v_cedula != null ?
                new ObjectParameter("v_cedula", v_cedula) :
                new ObjectParameter("v_cedula", typeof(string));
    
            var v_nombreParameter = v_nombre != null ?
                new ObjectParameter("v_nombre", v_nombre) :
                new ObjectParameter("v_nombre", typeof(string));
    
            var v_segundonombreParameter = v_segundonombre != null ?
                new ObjectParameter("v_segundonombre", v_segundonombre) :
                new ObjectParameter("v_segundonombre", typeof(string));
    
            var v_apellidoParameter = v_apellido != null ?
                new ObjectParameter("v_apellido", v_apellido) :
                new ObjectParameter("v_apellido", typeof(string));
    
            var v_segundoapellidoParameter = v_segundoapellido != null ?
                new ObjectParameter("v_segundoapellido", v_segundoapellido) :
                new ObjectParameter("v_segundoapellido", typeof(string));
    
            var v_emailParameter = v_email != null ?
                new ObjectParameter("v_email", v_email) :
                new ObjectParameter("v_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAdminRental_Result>("sp_RetornaAdminRental", v_cedulaParameter, v_nombreParameter, v_segundonombreParameter, v_apellidoParameter, v_segundoapellidoParameter, v_emailParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAdminRentalID_Result> sp_RetornaAdminRentalID(Nullable<int> id_admin)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAdminRentalID_Result>("sp_RetornaAdminRentalID", id_adminParameter);
        }
    }
}
